//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thinktecture.Wscf.Framework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Thinktecture.Wscf.Framework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;xs:schema id=&quot;RestaurantData&quot; targetNamespace=&quot;urn:thinktecture-com:demos:restaurantservice:data:v1&quot;
        ///	elementFormDefault=&quot;qualified&quot; xmlns=&quot;urn:thinktecture-com:demos:restaurantservice:data:v1&quot;
        ///	xmlns:mstns=&quot;urn:thinktecture-com:demos:restaurantservice:data:v1&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///  &lt;xs:element name=&quot;FooCollection&quot;&gt;
        ///    &lt;xs:complexType&gt;
        ///      &lt;xs:sequence&gt;
        ///        &lt;xs:element name=&quot;FooItem&quot; maxOccurs=&quot;unbounded&quot; minOccurs=&quot;0&quot; type=&quot;xs: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RestaurantDataXsd {
            get {
                return ResourceManager.GetString("RestaurantDataXsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;xs:schema id=&quot;RestaurantHeaderData&quot; targetNamespace=&quot;urn:thinktecture-com:demos:restaurantservice:headerdata:v1&quot;
        ///	elementFormDefault=&quot;qualified&quot; xmlns=&quot;urn:thinktecture-com:demos:restaurantservice:headerdata:v1&quot;
        ///	xmlns:mstns=&quot;urn:thinktecture-com:demos:restaurantservice:headerdata:v1&quot; xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///	&lt;xs:complexType name=&quot;credentials&quot;&gt;
        ///		&lt;xs:sequence&gt;
        ///			&lt;xs:element name=&quot;username&quot; type=&quot;xs:string&quot; /&gt;
        ///			&lt;xs:element name=&quot;password [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RestaurantHeaderDataXsd {
            get {
                return ResourceManager.GetString("RestaurantHeaderDataXsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema id=&quot;RestaurantMessages&quot; targetNamespace=&quot;urn:thinktecture-com:demos:restaurantservice:messages:v1&quot; 
        ///           elementFormDefault=&quot;qualified&quot; xmlns=&quot;urn:thinktecture-com:demos:restaurantservice:messages:v1&quot; 
        ///           xmlns:mstns=&quot;urn:thinktecture-com:demos:restaurantservice:messages:v1&quot; 
        ///           xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot; 
        ///           xmlns:import=&quot;urn:thinktecture-com:demos:restaurantservice:data:v1&quot;&gt;
        ///  &lt;xs:import id=&quot;RestaurantDa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RestaurantMessagesXsd {
            get {
                return ResourceManager.GetString("RestaurantMessagesXsd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Metadata xmlns=&quot;http://schemas.xmlsoap.org/ws/2004/09/mex&quot; xmlns:wsx=&quot;http://schemas.xmlsoap.org/ws/2004/09/mex&quot;&gt;&lt;wsx:MetadataSection Dialect=&quot;http://schemas.xmlsoap.org/wsdl/&quot; Identifier=&quot;http://www.thinktecture.com&quot; xmlns=&quot;&quot;&gt;&lt;definitions name=&quot;RestaurantService&quot; targetNamespace=&quot;http://www.thinktecture.com&quot; xmlns=&quot;http://schemas.xmlsoap.org/wsdl/&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns:import0=&quot;urn:thinktecture-com:demos:restaurantservice:messages:v1&quot; xmlns:tns=&quot;http://www.thinktecture.com&quot; x [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RestaurantMetadata {
            get {
                return ResourceManager.GetString("RestaurantMetadata", resourceCulture);
            }
        }
        
        internal static byte[] RestaurantServiceWsdl {
            get {
                object obj = ResourceManager.GetObject("RestaurantServiceWsdl", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
